version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: broccoli
    versions:
    - 3.5.0
  - dependency-name: sinon
    versions:
    - 9.2.2
  - dependency-name: release-it
    versions:
    - 14.2.2
  - dependency-name: mocha
    versions:
    - 8.2.1
